// src/app/home-header/home-header.component.ts
import { Component, AfterViewInit, ElementRef, ViewChild } from '@angular/core';
import { fillWithTag } from '../..//lib/handlers/handlersStyle';
import { htmlElementNotFound } from '../..//lib/handlers/handlersErrors';
import { PlaceholderKipperHeaderComponent } from '../placeholder-kipper-header/placeholder-kipper-header.component';

@Component({
  selector: 'app-home-header',
  templateUrl: `./home-header.component.html`,
  styleUrls: ['./home-header.component.scss'],
  standalone: true,
  imports: [PlaceholderKipperHeaderComponent],
})
export class HomeHeaderComponent implements AfterViewInit {
  @ViewChild('mainRef') mainRef!: ElementRef;
  ngAfterViewInit(): void {
    try {
      const headerElement = this.mainRef.nativeElement;
      if (
        !(
          headerElement instanceof HTMLElement &&
          headerElement.tagName === 'HEADER'
        )
      )
        throw htmlElementNotFound(
          headerElement,
          `validation of Main Reference in ${HomeHeaderComponent.prototype.constructor.name}`,
          ['<footer>']
        );
      fillWithTag(headerElement);
    } catch (e) {
      console.error(
        `Error executing ngAfterViewInit for mainRef in ${
          HomeHeaderComponent.prototype.constructor.name
        }:\n${(e as Error).message}`
      );
    }
  }
}

<header id="home-header" #mainRef class="sc-dcJsrY cXjjYJ">
  <app-placeholder-kipper-header></app-placeholder-kipper-header>
</header>

// portfolio-web-aronbo-app/src/app/components/headers/HomeHeader.tsx
import { nullishHeader } from "@/app/lib/declarations/types";
import { htmlElementNotFound } from "@/app/lib/handlers/handlersErrors";
import { fillWithTag } from "@/app/lib/handlers/handlersStyle";
import { useEffect, useRef } from "react";
import PlaceholderKipperHeader from "./PhKipperHeader";

export default function HomeHeader(): JSX.Element {
  const mainRef = useRef<nullishHeader>(null);
  useEffect(() => {
    try {
      if (
        !(
          mainRef.current instanceof HTMLElement &&
          mainRef.current.tagName === "HEADER"
        )
      )
        throw htmlElementNotFound(
          mainRef.current,
          `validation of Main Reference in ${HomeHeader.prototype.constructor.name}`,
          ["<footer>"]
        );
      fillWithTag(mainRef.current);
    } catch (e) {
      console.error(
        `Error executing useEffect for mainRef in ${
          HomeHeader.prototype.constructor.name
        }:\n${(e as Error).message}`
      );
    }
  }, [mainRef]);
  return (
    <header id="home-header" ref={mainRef} className="sc-dcJsrY cXjjYJ">
      <PlaceholderKipperHeader />
    </header>
  );
}
