// portfolio-web-aronbo-app/src/app/components/mainBodies/HomeMainBody.tsx
import { nullishMain } from "@/app/lib/declarations/types";
import { htmlElementNotFound } from "@/app/lib/handlers/handlersErrors";
import { fillWithTag } from "@/app/lib/handlers/handlersStyle";
import Image from "next/image";
import { useEffect, useRef } from "react";
import PlaceHolderKipperMain from "./PhKipperMain";

export default function HomeMainBody() {
  const mainRef = useRef<nullishMain>(null);
  useEffect(() => {
    try {
      if (
        !(
          mainRef.current instanceof HTMLElement &&
          mainRef.current.tagName === "MAIN"
        )
      )
        throw htmlElementNotFound(
          mainRef.current,
          `validation of Main Reference in ${HomeMainBody.prototype.constructor.name}`,
          ["<footer>"]
        );
      fillWithTag(mainRef.current);
    } catch (e) {
      console.error(
        `Error executing useEffect for mainRef in ${
          HomeMainBody.prototype.constructor.name
        }:\n${(e as Error).message}`
      );
    }
  }, [mainRef]);
  return (
    <main id="home-main">
      <PlaceHolderKipperMain />
    </main>
  );
}

// src/app/home-main-body/home-main-body.component.ts
import { Component, AfterViewInit, ElementRef, ViewChild } from '@angular/core';
import { fillWithTag } from '../..//lib/handlers/handlersStyle';
import { htmlElementNotFound } from '../..//lib/handlers/handlersErrors';
import { MainComponent } from '../main/main.component';

@Component({
  selector: 'app-home-main-body',
  templateUrl: `./home-main-body.component.html`,
  styleUrls: ['./home-main-body.component.scss'],
  standalone: true,
  imports: [MainComponent],
})
export class HomeMainBodyComponent implements AfterViewInit {
  @ViewChild('mainRef') mainRef!: ElementRef;
  ngAfterViewInit(): void {
    try {
      const mainElement = this.mainRef.nativeElement;
      if (
        !(mainElement instanceof HTMLElement && mainElement.tagName === 'MAIN')
      )
        throw htmlElementNotFound(
          mainElement,
          `validation of Main Reference in ${HomeMainBodyComponent.prototype.constructor.name}`,
          ['<main>']
        );
      fillWithTag(mainElement);
    } catch (e) {
      console.error(
        `Error executing ngAfterViewInit for mainRef in ${
          HomeMainBodyComponent.prototype.constructor.name
        }:\n${(e as Error).message}`
      );
    }
  }
}

<main id="home-main" #mainRef>
  <app-main />
</main>
