// portfolio-web-aronbo-app/src/app/components/footers/HomeFooter.tsx
import { nullishFooter } from "@/app/lib/declarations/types";
import { htmlElementNotFound } from "@/app/lib/handlers/handlersErrors";
import { fillWithTag } from "@/app/lib/handlers/handlersStyle";
import { useEffect, useRef } from "react";

export default function HomeFooter(): JSX.Element {
  const mainRef = useRef<nullishFooter>(null);
  useEffect(() => {
    try {
      if (
        !(
          mainRef.current instanceof HTMLElement &&
          mainRef.current.tagName === "FOOTER"
        )
      )
        throw htmlElementNotFound(
          mainRef.current,
          `validation of Main Reference in ${HomeFooter.prototype.constructor.name}`,
          ["<footer>"]
        );
      fillWithTag(mainRef.current);
    } catch (e) {
      console.error(
        `Error executing useEffect for mainRef in ${
          HomeFooter.prototype.constructor.name
        }:\n${(e as Error).message}`
      );
    }
  }, [mainRef]);
  return <footer id="home-footer" ref={mainRef}></footer>;
}

// src/app/home-footer/home-footer.component.ts
import { Component, AfterViewInit, ViewChild, ElementRef } from '@angular/core';
import { fillWithTag } from '../..//lib/handlers/handlersStyle';
import { htmlElementNotFound } from '../..//lib/handlers/handlersErrors';

@Component({
  selector: 'app-home-footer',
  templateUrl: `./home-footer.component.html`,
  styleUrls: ['./home-footer.component.scss'],
  standalone: true,
  imports: [],
})
export class HomeFooterComponent implements AfterViewInit {
  @ViewChild('mainRef') mainRef!: ElementRef;
  ngAfterViewInit(): void {
    try {
      const footerElement = this.mainRef.nativeElement;
      if (
        !(
          footerElement instanceof HTMLElement &&
          footerElement.tagName === 'FOOTER'
        )
      )
        throw htmlElementNotFound(
          footerElement,
          `validation of Main Reference in ${HomeFooterComponent.prototype.constructor.name}`,
          ['<footer>']
        );
      fillWithTag(footerElement);
    } catch (e) {
      console.error(
        `Error executing ngAfterViewInit for mainRef in ${
          HomeFooterComponent.prototype.constructor.name
        }:\n${(e as Error).message}`
      );
    }
  }
}

<footer id="home-footer" #mainRef></footer>
