// portfolio-web-aronbo-app/src/app/components/home.tsx
"use client";

import { createContext, useEffect, useState } from "react";
import HomeFooter from "./footers/HomeFooter";
import HomeHeader from "./headers/HomeHeader";
import HomeMainBody from "./mainBodies/HomeMainBody";
import { voidishAppContext } from "../lib/declarations/types";
import { useDispatch } from "react-redux";
import { setRouter } from "../redux/slices/routerSlice";
import { RoutedProps } from "../lib/declarations/interfacesProps";
import { applyDefaultPoppins } from "../lib/handlers/handlersStyle";

export const AppHomeContext = createContext<voidishAppContext>(undefined);

export default function Home(props: RoutedProps) {
  const dispatch = useDispatch();
  const [_, setDispatch] = useState<boolean>(false);
  useEffect(() => {
    dispatch(setRouter(props.routerState));
    setDispatch(true);
  }, [dispatch]);
  useEffect(() => {
    applyDefaultPoppins();
    addEventListener("copy", ev => {
      console.log(
        ev.clipboardData?.items
          .add(
            new File(
              [
                "Hello, File",
                JSON.stringify({ key: "value" }),
                new Uint16Array([0x0000, 0xffff, 0x7fff]),
              ],
              "newFile.txt"
            )
          )
          ?.webkitGetAsEntry()
      ); //ClipboardEvent //DataTransfer //DataTransferItemList //FileSystemEntry);
    });
  }, []);
  return (
    <div id="homeRoot">
      <AppHomeContext.Provider value={{ router: undefined }}>
        <HomeHeader />
        <HomeMainBody />
        <HomeFooter />
        <div id="modalRoot" style={{ width: "0", height: "0" }}></div>
      </AppHomeContext.Provider>
    </div>
  );
}

// src/app/home/home.component.ts
import { Component, OnInit, AfterViewInit, Inject } from '@angular/core';
// import { DOCUMENT } from '@angular/common';
// import { Store } from '@ngrx/store';
import { applyDefaultPoppins } from '../..//lib/handlers/handlersStyle';
import { HomeFooterComponent } from '../home-footer/home-footer.component';
import { HomeMainBodyComponent } from '../home-main-body/home-main-body.component';
import { HomeHeaderComponent } from '../home-header/home-header.component';

@Component({
  selector: 'app-home',
  templateUrl: `./home.component.html`,
  styleUrls: ['./home.component.scss'],
  standalone: true,
  imports: [HomeFooterComponent, HomeMainBodyComponent, HomeHeaderComponent],
})
export class HomeComponent implements OnInit, AfterViewInit {
  // constructor(
  //   // private store: Store,
  //   // @Inject(DOCUMENT) private document: Document
  // ) {}
  ngOnInit(): void {
    //   this.store.dispatch(setRouter({ routerState: this.document.location }));
  }
  ngAfterViewInit(): void {
    applyDefaultPoppins();
    addEventListener('copy', (ev: ClipboardEvent) => {
      console.log(
        ev.clipboardData?.items
          .add(
            new File(
              [
                'Hello, File',
                JSON.stringify({ key: 'value' }),
                new Uint16Array([0x0000, 0xffff, 0x7fff]),
              ],
              'newFile.txt'
            )
          )
          ?.webkitGetAsEntry()
      );
    });
  }
}

<div id="homeRoot">
  <!-- <app-home-header></app-home-header> -->
  <app-home-main-body></app-home-main-body>
  <app-home-footer></app-home-footer>
  <div id="modalRoot" style="width: 0; height: 0"></div>
</div>
